services:
  mysql_service:
    restart: unless-stopped
    image: mysql:9.0.1
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./secrets/mysql:/secrets/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/secrets/mysql/root_password.txt"
      MYSQL_DATABASE_FILE: "/secrets/mysql/database.txt"
      MYSQL_USER_FILE: "/secrets/mysql/user.txt"
      MYSQL_PASSWORD_FILE: "/secrets/mysql/password.txt"
    ports:
      - "3306:3306"
    networks:
      - mysql_network

volumes:
  mysql_volume:

networks:
  mysql_network:
